services:
  postgres:
    container_name: postgres
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: meownation
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped
  cache:
    container_name: redis_container
    image: redis:6.2-alpine
    restart: always
    ports:
       - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
       - cache:/data
    networks:
      - network
  app:
    build: .
    networks:
      - network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cache
    environment:
#      - JAVA_OPTS=-Dspring.config.location=file:/config/application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/meownation
      - SPRING_DATASOURCE_USERNAME= meownation
      - SPRING_DATASOURCE_PASSWORD= password123
      - SPRING_REDIS_HOST=cache
#      - SPRING_REDIS_PORT=6379
#      - SPRING_REDIS_PASSWORD= eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - D:\spring\astromvc1\config\:/config/

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - network
    restart: unless-stopped



volumes:
  cache:
    driver: local
  postgres:
  pgadmin:

networks:
  network:
    driver: bridge
