app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/meownation
      username: meownation
      password: password123
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /daily/add:
    post:
      tags:
        - daily-horoscope-controller
      operationId: postDailyHoroscope
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DailyHoroscopeResult'
        required: true
      responses:
        "201":
          description: Created
  /daily:
    get:
      tags:
        - daily-horoscope-controller
      operationId: getAllSigns
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  enum:
                    - ARIES
                    - TAURUS
                    - GEMINI
                    - CANCER
                    - LEO
                    - VIRGO
                    - LIBRA
                    - SCORPIO
                    - SAGITTARIUS
                    - CAPRICORN
                    - AQUARIUS
                    - PISCES
                    - UNKNOWN
  /daily/{astroSign}:
    get:
      tags:
        - daily-horoscope-controller
      operationId: getDailyHoroscope
      parameters:
        - name: astroSign
          in: path
          required: true
          schema:
            type: string
            enum:
              - ARIES
              - TAURUS
              - GEMINI
              - CANCER
              - LEO
              - VIRGO
              - LIBRA
              - SCORPIO
              - SAGITTARIUS
              - CAPRICORN
              - AQUARIUS
              - PISCES
              - UNKNOWN
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DailyHoroscopeResult'
components:
  schemas:
    DailyHoroscopeResult:
      type: object
      properties:
        payload:
          type: string
        date:
          type: string
          format: date-time
        sign:
          type: string
          enum:
            - ARIES
            - TAURUS
            - GEMINI
            - CANCER
            - LEO
            - VIRGO
            - LIBRA
            - SCORPIO
            - SAGITTARIUS
            - CAPRICORN
            - AQUARIUS
            - PISCES
            - UNKNOWN
