app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/meow
      username: meow
      password: 'nation'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
