app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://postgres:5432/meownation
      username: meownation
      password: password123
      pool-size: 30
spring:
  redis:
#    host: redis_container
    port: 6379

server:
  error:
    include-binding-errors: always
    include-message: always

openapi: 3.0.1
info:
  title: OpenAPI AstroMVC
  version: v0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
