INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ne razumete partnerov stav o zajedničkom problemu, imate utisak da se nalazite na suprotnim stranama.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Izbegavajte napete situacije u susretu sa voljenom osobom, važno je da među Vama postoje dobre namere.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema potrebe da strahujete od istine ili da potiskujete svoje želje u društvu bliske osobe.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Mogući su različiti konflikti ili nerazumevanje, voljena osoba kao da nema previše razumevanja za Vaše ćudljivo ponašanje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Očekuje Vas prijatno iznenađenje u susretu sa voljenom osobom. Budite dovoljno maštoviti i inspirativni u svakom pogledu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Stvari ponekad izgledaju potpuno drugačije od prvog utiska koji imate. Postupite po svojoj savesti u susretu sa voljenom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nemojte davati velika i ishitrena obećanja voljenoj osobi. Moguće je da ćete se više puta predomisliti.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Često menjate svoje raspoloženje ili odluke. Veću važnost ima ono što prećutkujete, nego stvari koje saopštavate partneru.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema potrebe da se sukobljavate sa bliskom osobom. Emotivne nesuglasice nisu značajne za nove događaje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Priuštite svojoj porodici ili voljenoj osobi dobru zabavu. Uz iskrene namere usrećite osobu do koje Vam je stalo.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Za sada vešto korisite svoje sposobnosti na različitim stranama. Partner ne može da odoli Vašem šarmu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Delujete uznemireno, teško pronalazite svoju »mirnu luku« i emotivni predah. Nedostaje Vam poverenje u jednu blisku osobu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Razgovarajte otvoreno sa partnerom i insistirajte na dokazivanju istine. Ne treba da se zavaravate iluzijama.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U odnosu sa voljenom osobom nemojte tražiti nemoguće ustupke, sa više poštovanja prihvatite ono što dobijate.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ukoliko Vam je stalo da obradujete partnera, razmislite na koji način treba da predstavite svoje ideje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nemojte dozvoliti da Vam nedostaju maštovitost ili emotivna inspiracija. Partner budnim okom prati Vaše kretanje i ponašanje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema razloga da se ponašate strogo prema partneru. Pokažite da imate dovoljno razumevanja i emotivnog sluha.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Iznenadite voljenu osobu ne neki nesvakidašnji način, ako imate dovoljno mašte sve je moguće promeniti u pozitivnom pravcu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema razloga da se ponašate strogo prema partneru. Pokažite da imate dovoljno razumevanja i emotivnog sluha.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Iznenadite voljenu osobu ne neki nesvakidašnji način, ako imate dovoljno mašte sve je moguće promeniti u pozitivnom pravcu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U momentima delujete tajanstveno, ali partner nema dovoljno interesovanja ili volje da odgoneta Vaše misli.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U emotivnom životu, partner pokušava da Vam pomogne ili da Vas oraspoloži. Međutim, Vi reagujete na suprotan način.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U odnosu sa voljenom osobom, postavite jasnu granicu između pristojnog ponašanja i uzajamnog poverenja.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U emotivnom smislu, očekuje Vas novo zadovoljstvo koje će obeležiti Vas odnos sa voljenom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Vaše emotivno raspoloženje i zadovoljstvo se menja u zavisnosti od različitih susreta. Ponekad delujete zbunjeno i neodlučno.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Izbegavajte napete situacije u susretu sa voljenom osobom, važno je da među Vama postoje dobre namere.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Razgovarajte otvoreno sa partnerom i insistirajte na dokazivanju istine. Ne treba da se zavaravate iluzijama.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Planirajate susret ili neku atraktivnu zabavu u dvoje. Ako ne pokušate, pokajaćete se.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Svoj uspeh možete da afirmišete u različitim situacijama, a svoj šarm ili neodoljivost pred bliskom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ponekad određene »sitnice« više otkrivaju nego rečenice koje se uporno ponavaljaju. Pažljivije analizirajte voljenu osobu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Budite dovoljno opušteni, prepustite partneru glavnu ulogu u zajedničkim planovima. Nema razloga da se prepirete oko sitnica.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner ne želi lako da se odrekne planova koje ima. Ali, neko mora prvi da popusti. Budite mudri.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Vaša pojava ili stil deluju izazovno na voljenu osobu, što predstavlja dobar ljubavni predznak. Prijaće Vam nečije blisko društvo.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema potrebe da gajite velike iluzije ili emotivna očekivanja, pred osobom koju ne poznajete dovoljno. Lako se zanosite.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Potrebno je da delujete opuštenije pred bliskom osobom. Prepustite partneru zapaženu ulogu u bliskom kontaktu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U duhu emotivne inspiracije planirajte romantičnu zabavu ili novi ljubavni susret. Prijaće Vam nečija pažnja i naklonost.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Pažljivo analizirate voljenu osobu, ali ne možete da uskladite različite aspiracije i interesovanja koja Vas udaljavaju.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Novi događaj ili nesporazum koji vas brine, ne ostavlja bitne posledice na odnos sa voljenom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ukoliko vam smeta osećaj monotonije u emotivnom odnosu, potrudite se da iznenadite voljenu osobu na neobičan način.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner ne može da vam dočara sve ono što biste želeli da čujete ili vidite. Na žalost, ostajete uskraćeni za različite potrebe.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Potrebno da razumete nečiju emotivnu slabost. Nema razloga da se ponašate nadmeno u društvu bliske osobe.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Stvari ponekad izgledaju potpuno drugačije od prvog utiska koji imate. Postupite po svojoj savesti u susretu sa voljenom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Potrebno je da dokažete svoje iskrene namere i dobru volju pred voljenom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Planirajte susret sa osobom koja u vama pokreće emotivne talase, potreban vam je pozitivan impuls. Oslonite se na snagu svojih osećanja.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Godi vam nečije emotivno interesovanje, ali potajno priželjkujete da oprobate svoje sposobnosti u novom društvu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner ima poverenje u vaše sposobnosti i prepušta vam da donesete odluku u zajedničko ime. Ne želite da vas neko previše obavezuje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Delujete zavodljivo i privlačno. Sreća je na vašoj strani, sve dok postoji zajednička želja da sačuvate emotivnu bliskost.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Stvari koje vama izgledaju interesantno, partner posmatra sa određenom dozom nepoverenja i ima drugačiju teoriju.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Moguće je da ste nehotično povredili nečija osećanja, glas savesti vas podseća na iskreno izvinjenje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ponekad vaš ljubavni život nije dovoljno interesantan i uzbudljiv koliko biste to želeli, ali vi imate dobru volju da to promenite.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Sa druge strane, preterana doza hrabrosti ili emotivne samovolje može da iskomplikuje zajednički život i odnos sa bliskom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U emotivnom smislu, brinete bez pravog razloga. Voljena osoba trenutno ne želi da vam poverava svoje misli. Sami postupci dovoljno govore o nečijim osećanjima.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Potrebna vam je dobra volja i veliko strpljenje da se uzdržite u nekim reakcijama pred voljenom osobom. Imate različite stavove i viđenja.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Prati vas emotivno zatišje. Utonuli ste u svoj svet ideja i iščekujete promene ili da neko u vama pokrene snažne impulse.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner često postavlja pitanja koja u vama podstiču nelagodnost ili loš predosećaj. Suviše strepite od nečije reakcije.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U odabranom društvu i uz nečije emotivne podsticaje, svet oko vas izgleda mnogo bolje i lepše. Opustite se uz blisku osobu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Umesto da nepotrebno morališete i pridikujete za različite sitnice koje primećujete, potrudite se da ulepšate nečije emotivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'U susretu sa voljenom osobom upotrebite neki oprobani recept, koji vodi ka novom emotivnom i strasnom zblizavanju. Kao i uvek, dobra volja – čuda čini.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Pažljivije analizirajte voljenu osobu kako biste otkrili nove detalje koji mogu da ispune zajednička očekivanja i potrebe koje imate.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ako vam je zaista stalo do ljubavnog pomirenja, pružite novu priliku svom partneru. Nije teško pokazati da imate dobre namere.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Budite umerenji u zahtevima prema voljenoj osobi. Prijaće Vam susret sa bliskim prijateljima i nečija pažnja.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Prijaće Vam susret sa bliskom osobom i emotivna pažnja. Učinite sve što je potrebno da ostvarite zajedničko zadovoljstvo.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Sujeta Vas navodi na pogrešan zaključak. Razmislite zbog čega partner deluje nezainteresovano.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Priželjkujete zanimljivije događaje u ljubavnom životu. Susret sa jednom osobom može da Vam popravi raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner se žali na Vašu učestalu rasejanost ili zaboravnost. Ispravite na vreme svoje propuste.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Osmislite dobar plan i originalan nastup koji treba da zadovolji blisku osobu. Važno je da napravite dobar izbor u svakom pogledu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Priuštite svojoj porodici ili voljenoj osobi dobru zabavu. Uz iskrene namere usrećite osobu do koje Vam je stalo.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Neko Vas uzbuđuje ili Vam privlači pažnju, više nego što ste spremni da priznate. Delujete tajanstveno.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Sve više počinje da Vam nedostaje nečije prisustvo ili emotivna pažnja. Nema razloga da potiskujete svoja osećanja i potrebe.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema razloga da prikrivate deo priče pred bliskom osobom. Suočavanje sa istinom predstavlja psihološko olakšanje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Preterana doza hrabrosti ili samovolje, može da iskomplikuje zajednički život i odnos sa bliskom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Ako vam je zaista stalo do ljubavnog pomirenja, pružite novu priliku svom partneru. Nije teško pokazati da imate dobre namere.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Sujeta Vas navodi na pogrešan zaključak. Razmislite zbog čega partner deluje nezainteresovano.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Priželjkujete zanimljivije događaje u ljubavnom životu. Susret sa jednom osobom može da Vam popravi raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Partner se žali na Vašu učestalu rasejanost ili zaboravnost. Ispravite na vreme svoje propuste.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Osmislite dobar plan i originalan nastup koji treba da zadovolji blisku osobu. Važno je da napravite dobar izbor u svakom pogledu.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Priuštite svojoj porodici ili voljenoj osobi dobru zabavu. Uz iskrene namere usrećite osobu do koje Vam je stalo.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Neko Vas uzbuđuje ili Vam privlači pažnju, više nego što ste spremni da priznate. Delujete tajanstveno.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Sve više počinje da Vam nedostaje nečije prisustvo ili emotivna pažnja. Nema razloga da potiskujete svoja osećanja i potrebe.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Nema razloga da prikrivate deo priče pred bliskom osobom. Suočavanje sa istinom predstavlja psihološko olakšanje.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Preterana doza hrabrosti ili samovolje, može da iskomplikuje zajednički život i odnos sa bliskom osobom.');
INSERT INTO paragraph(topic,text) values ('Ljubav', 'Neko Vas uzbuđuje ili Vam privlači pažnju, više nego što ste spremni da priznate. Delujete tajanstveno.');

INSERT INTO paragraph(topic,text) values ('Posao', 'Izbegavajte sumnjive okolnosti i pažljivije analizirajte svoje saradnike. Ponekad postoje »skriveni detalji« koji se teže uočavaju.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko Vam je stalo da testirate svoje intelektualne ili praktične sposobnosti, potrebno je da imate precizne ciljeve.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Sve ima svoju granicu ili cenu, tako i radna terapija ima pozitivne efekte samo pod određenim uslovima');
INSERT INTO paragraph(topic,text) values ('Posao', 'Očekujete pozitivan odgovor ili povratnu informaciju o poslovnoj saradnji, međutim sve je obavijeno velom neizvesnosti.');
INSERT INTO paragraph(topic,text) values ('Posao', 'U zajedničkom interesu je da se poslovno-finansijski rizik svede na minimum. Korektno poštujte dogovor.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Obratite pažnju na koristan savet, uvek postoji mogućnost da se ostvari poslovni dogovor koji vodi u pravcu zajedničkih rešenja.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Objašnjavate stvari koje Vaša okolina dobro poznaje, ali se ne usuđuje i da ih prihvati.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko Vama podstiče kreativnu radoznalošt i želju za novim saznanjima. Vaši ciljevi su dostižni uz pravilno rasuđivanje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko ne obraća pažnju na Vaš poslovni autoritet ili komentare koje upućujete. Potrebno je da uspostavite bolji model uspešne komunikacije.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko osporava Vaše ideje ili uticaj koji imate u poslovnim krugovima. Sa par dobrih poteza, možete rešiti svoje probleme.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Umete da uspostavite dobru poslovnu kontrolu i da usmeravate događaje u pravcu koji donosi praktične rezultate.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Polazite od pogrešnih informacija, tako da Vaše prognoze zvuče neubedljivo. Prihvatite dobronamernu kritiku.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Potrebno je da završite svoje obaveze u predviđenom roku. Neko neće tolerisati Vaše izgovore ili poslovne propuste.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Uvek postoji i lakši i teži put do uspeha, stoga prihvatite korisnu ideju koju predlažu Vaši saradnici.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Poslovni uspeh podrazumeva novu i dobro osmišljenu akciju, prihvatite izazov u skladu sa svojim potrebama.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko Vam je stalo da testirate svoje intelektualne ili praktične sposobnosti, potrebno je da imate precizne ciljeve.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Opterećeni ste novim poslovnim planovima. Reagujete suviše temperamentno u situacijama kada treba pokazati diplomatske manire.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Na Vama je da stvorite osnovne uslove i da pokrenete glavnu inicijativu, a na nekom drugom da uspešno realizuje Vaše ideje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Postoje događaji na koje nemate veliki uticaj, jer neko drugi određuje pravila. Prihvatite ponuđeno rešenje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Važno je da ne pričate previše pred osobom koja može da Vas okarakteriše na pogrešan način. Budite diskretni.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko Vam nedostaju pouzdane informacije o poslovnim prilikama nemojte davati lakomislena obećanja, već zatražite nečije posredovanje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Susret sa jednom osobom na Vas deluje intrigantno, zbog toga ne uspevate da prikrijete svoje neraspoloženje i zabrinutost.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Trenutak je da ubrzate svoje poslovne aktivnosti. Za bliskog saradnika odaberite osobu za koju Vas vezuju zajednički interesi.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Važno je da pravilno zaštitite svoje poslovne interese. Postavite jasnu granicu do koje ste spremni da preuzmete odgovornost.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ne treba da dovodite u pitanje naklonost proverenih saradnika, naročito osobe za koju Vas vezuju poslovni i privatni interesi.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Vaša okolina deluje pozitivno i neko velikodušno ispunjava zahteve koje postavljate.');
INSERT INTO paragraph(topic,text) values ('Posao', 'U zajedničkom interesu je da se poslovno-finansijski rizik svede na minimum. Korektno poštujte dogovor.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Osoba koja misli poput vas ima i slične poslovne interese, neće vam dozvoliti da ostvarite svoje ciljeve.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Osećate potrebu da zavedete red u svojoj okolini, ali to činite na loš način ili u pogrešnom trenutku. Izbegavajte brzopletost.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ne verujete u nečija ponovljena obećanja, stoga tražite ubedljive dokaze ili dodatnu garanciju za poslovni dogovor.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Bez obzira na vašu snalažljivost, ne možete da kontrolišete niz događaja na poslovnoj sceni i svoje saradnike.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ne treba da se opterećujete različitim kriterijumima. Svako od saradnika ima svoju interpretaciju događaja.');
INSERT INTO paragraph(topic,text) values ('Posao', 'U društvu saradnika delujete samouvereno, ambiciozno i vrlo zahtevno u svakom pogledu.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko vas opterećuje test situacijama. Nemojte dozvoliti da poslovni nesporazumi utiču na vaše kretivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Delujete vrlo samouvereno, potrudite se da ostvarite dobar poslovni kontakt na različitim stranama.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Imate zanimljive ideje. Blic procena predstavlja značajnu prednost u donošenju novih odluka, oslonite se i na svoje inutitivno opažanje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko potvrđuje vaša očekivanja u poslovnoj saradnji. Važno je da sačuvate prisebnost duha odlučujućem momentu.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Nema potrebe da žalite za propuštenom prilikom, bliski saradnici neće dozvoliti da trpite zbog sitnih interesa.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Pravilna informisanost pruža širu mogućnost za dobar izbor i poslovnu afirmaciju. Vaši saradnici imaju dobre ideje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Nalazite se pred novom poslovnom dilemom i potreban vam je nečiji dobar savet. Ne treba da precenjujete svoje mogućnosti. Stalo vam je da održite nivo uspešne saradnje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko nemate dovoljno interesovanja da se posvetite nekim zamornim temama, budite iskreni i nemojte davati zvanična obećanja. Nedostaje vam bolja koncentracija.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Bez obzira na vašu intelektualnu snalažljivost i efikasnost, postoje stvari koje se ne uklapaju u vašu poslovnu procenu. Nečija kritika donosi negativan efekat.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ako prekršite osnovna poslovna pravila, postoji mogućnost da vam se pripiše veći deo krivice nego što to zaslužujete. Bolje je da svoje obaveze zavrsite na rutinski način.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Zainteresovani ste za neke savremenije ideje i pokušavate da se rasteretite od napornih obaveza. Pažljivije analizirajte svoje saradnike. Neko vam daje dobar primer o uspešnom poslovanju.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Teško vam je da se organizujete kada vas saradnici neprekidno ometaju sa različitim zahtevima. Stalo vam je da ostvarite saglasnost oko zajedničkih interesa.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Koristite stroge kriterijume kako biste maksimalno zaštitili svoje interese u poslovnim pregovorima. Ne treba da se ponašate suviše strogo prema osobi koja ima dobru nameru.');
INSERT INTO paragraph(topic,text) values ('Posao', 'U poslovnom dijalogu postoje stvari koje ne treba da činite u afektu ili na osnovu prvog impulsa. Neko od saradnika pažljivo analizira vaše ponašanje i donosi ocenu.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ponekad sve postaje relativno i podložno iznenadnim promenama i zato nemojte donositi zaključak bez konsultacije sa bliskim saradnicima. Izbegavajte varijantu sve ili ništa.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ponekad treba upotrebiti poznato šahovsko pravilo: „taknuto-maknuto“. Saradnici očekuju da delujete dovoljno snalažljivo u različitim situacijama i prilikama.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Imate dobru nameru, ali postoje iznenadne okolnosti koje vas sputavaju da ostvarite svoje poslovne planove. Bolje je da se zaustavite u nekom kritičnom trenutku.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Pravilna informisanost pruža širu mogućnost za dobar izbor i poslovnu afirmaciju. Vaši saradnici imaju dobre ideje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Neko Vam na indirektan način daje do znanja da svaka usluga ima svoju povratnu cenu i značenje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Očekuje Vas pozitivan rasplet događaja pod uslovom da konsultujete prijatelje i sačuvate prisebnost.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Potrudite se da pravilno razgraničite svoje obaveze od interesa koji Vas vezuju za određene saradnike. Ne treba da trpite nečiju samovolju.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Tek kada budete spoznali pravu istinu, shvatićete na koji način treba da rešavate svoje poslovno-finansijske dileme.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko ste zainteresovani za nove poslovne izazove, potrebna Vam je dobra procena. Upotrebite »moć sugestije« u pregovorima.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko budete dovoljno efikasni, predstoji Vam novi dobitak i moralna satisfakcija. Nemojte propustiti dobru priliku.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Dobar izbor proizilazi iz pouzdanih konsultacija. Važno je da u profesionalnom maniru ispunite različita očekivanja.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Sa par dobrih poteza, možete da učinite više nego Vaši saradnici. Možete da ostvarite svoje namere na različitim stranama.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Suočavate se sa različitim problemima. Većina saradnika zagovara merila ili uslove koje najbolje poznaje.');
INSERT INTO paragraph(topic,text) values ('Posao', 'Ukoliko nemate interesovanja da se posvetite nekim zamornim temama, budite iskreni i nemojte davati zvanična obećanja.');

INSERT INTO paragraph(topic,text) values ('Zdravlje', 'U večernjim satima prijaće Vam izlazak, šetnja ili relaksacija.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Potrudite se da pravilno usmeravate svoju pozitivnu energiju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Olakšajte svoju savest, prijaće Vam relaksacija.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Obratite pažnju na zdraviji način ishrane, izbegavajte neke »loše« navike.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Obratite pažnju na svoje zdravstvene mogućnosti i ne testirajte ih.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Nalazite se u sjajnoj formi.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće Vam rekreacija ili boravak u prirodi.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da akumulirate pozitivnu energiju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Zračite pozitivnom energijom i dobrim raspoloženjem.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da sačuvate pozitivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Izbegavajte destruktivno ponašanje i loše navike.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Ulepšajte svoj izgled, kao podsticaj za dobro raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da pravilno kanališete svoju energiju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Potrebno je da poboljšate svoju psiho-fizičku kondiciju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Potrebno je da se rasteretite suvišnih briga');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da sačuvate dobro raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'U večernjim satima prijaće Vam izazak ili šetnja.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Izbegavajte neke loše navike.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće Vam izlazak ili boravak u prirodi.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće Vam psihofizička relaksacija.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da pravilno usmeravate svoju kreativnu energiju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Poboljašajte svoju psihofizičku kondiciju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Budite promišljeni.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Podstičite kod sebe dobro raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Različiti sadržaji zabave deluju pozitivno na Vaše raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Podstičite kod sebe pozitivne misli, opustite se.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće vam izlazak ili boravak u prirodi i opuštanje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Večernje sate planirajte da provedete u interesantnom društvu i u opuštenoj atmosferi.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Izbegavajte suviše naporne ili stresne situacije.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Rasteretite se od suvišnih briga, popravite raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Nema potrebe da se oterećujete teškim mislima.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da sačuvate prisebnost duha i pozitivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Važno je da pravilno usmeravate svoju kreativnu energiju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće vam šetnja i neki vid relaksacije, kao opuštanje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Potrebno je da uskladite svoje želje i mogućnosti, izbegavajte preterivanje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Nema razloga da se opterećujete novim sumnjama.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Dobro se osećate.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Podstičite kod sebe koncentraciju i pozitivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće Vam kreativan odmor i više sati zdravog sna.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Izbegavajte depresivno raspoloženje i destruktivno ponašanje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Prijaće Vam neka dodatna aktivnost, kao psihološka relaksacija.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Podstičite kod sebe dobro raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Izbegavajte loše navike ili depresivno raspoloženje.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'U večernjim satima prijaće Vam izlazak ili šetnja.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Obratite pažnju na snove.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Posvetite pažnju stvarima koje Vas duhovno ispunjavaju.');
INSERT INTO paragraph(topic,text) values ('Zdravlje', 'Obratite pažnju na pravilnu ishranu.');

